name: Deploy Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      working-directory: server
      run: npm install

    # If build is not necessary, remove this step
    # - name: Build application
    #   working-directory: server
    #   run: npm run build

    - name: Start application
      working-directory: server
      env:
        GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
        SHEET_ID: ${{ secrets.SHEET_ID }}
        PORT: ${{ secrets.PORT }}
      run: npm start
